### ISSUE TITLE
FITS save handler not installed ??

### ISSUE THREAD

**Issue by edwardcho** [JeongHyunJin/Pix2PixHD#3]
Hello Sir,

I met another problem.
```python
'''
the number of G parameters 182430721
  0%|                                                                                                                    | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "Pix2PixHD_Test.py", line 136, in <module>
    pil_image.save(os.path.join(dir_image_save, name[0] + '_AI.fits'))
  File "/home/itsme/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 1994, in save
    save_handler(self, fp, filename)
  File "/home/itsme/anaconda3/lib/python3.7/site-packages/PIL/FitsStubImagePlugin.py", line 65, in _save
    raise IOError("FITS save handler not installed")
OSError: FITS save handler not installed
```

What should I do for this problem??
Thanks.

**Comment by davidvfx07** [comment]
In Pix2PixHD_Test.py, line 136, change `dir_image_save, name[0] + '_AI.fits'` to `dir_image_save, name[0] + '_AI.png'`
